#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  poc:

services:
  skcc_peer2:
    container_name: skcc_peer2
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=skcc_peer2
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=skcc
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_ADDRESS=skcc_peer2:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_poc
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=skcc_couchdb2:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      # - CORE_OPERATIONS_LISTENADDRESS=skcc_peer2:9443
      # - CORE_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
      # - 8443:9443      
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/skcc/peers/skcc_peer2/msp:/etc/hyperledger/msp
      - ./crypto-config/peerOrganizations/skcc/peers/skcc_peer2/tls:/etc/hyperledger/tls
      # - ./poc-network/skcc_peer2:/var/hyperledger/production
    # depends_on:
      # - skcc_couchdb2      
    networks:
      - poc

  # skcc_couchdb2:
  #   container_name: skcc_couchdb2
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "6984:5984"
  #   volume:
  #     - ./poc-network/skcc_couchdb2:/opt/couchdb/data  
  #   networks:
  #     - poc

  contractor1_peer2:
    container_name: contractor1_peer2
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=contractor1_peer2
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=contractor1
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_ADDRESS=contractor1_peer2:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_poc
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=contractor1_couchdb2:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      # - CORE_OPERATIONS_LISTENADDRESS=contractor1_peer2:9443
      # - CORE_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 10051:7051
      - 10053:7053
      # - 10443:9443         
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/contractor1/peers/contractor1_peer2/msp:/etc/hyperledger/msp
      - ./crypto-config/peerOrganizations/contractor1/peers/contractor1_peer2/tls:/etc/hyperledger/tls
      # - ./poc-network/contractor1_peer2:/var/hyperledger/production      
    # depends_on:
      # - contractor1_couchdb2      
    networks:
      - poc

  # contractor1_couchdb2:
  #   container_name: contractor1_couchdb2
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "8984:5984"
  #   volume:
  #     - ./poc-network/contractor1_couchdb2:/opt/couchdb/data  
  #   networks:
  #     - poc