#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  poc:

services:
  contractor2_peer1:
    container_name: contractor2_peer1
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=contractor2_peer1
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=contractor2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_ADDRESS=contractor2_peer1:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_poc
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=contractor2_couchdb1:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      # - CORE_OPERATIONS_LISTENADDRESS=contractor2_peer1:9443
      # - CORE_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 11051:7051
      - 11053:7053
      # - 11443:9443
    volumes:
      - /var/run/:/host/var/run/
      - ./contractor2-config/crypto-config/peerOrganizations/contractor2/peers/contractor2_peer1/msp:/etc/hyperledger/msp
      - ./contractor2-config/crypto-config/peerOrganizations/contractor2/peers/contractor2_peer1/tls:/etc/hyperledger/tls
      # - ./poc-network/contractor2_peer1:/var/hyperledger/production      
    # depends_on:
    #   - contractor2_couchdb1
    networks:
      - poc

  # contractor2_couchdb1:
  #   container_name: contractor2_couchdb1
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "9984:5984"
  #   volume:
  #     - ./poc-network/contractor2_couchdb1:/opt/couchdb/data
  #   networks:
  #     - poc    

  contractor2_peer2:
    container_name: contractor2_peer2
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=contractor2_peer2
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=contractor2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_ADDRESS=contractor2_peer2:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_poc
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=contractor2_couchdb2:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      # - CORE_OPERATIONS_LISTENADDRESS=contractor2_peer2:9443
      # - CORE_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 12051:7051
      - 12053:7053
      # - 12443:9443      
    volumes:
      - /var/run/:/host/var/run/
      - ./contractor2-config/crypto-config/peerOrganizations/contractor2/peers/contractor2_peer2/msp:/etc/hyperledger/msp
      - ./contractor2-config/crypto-config/peerOrganizations/contractor2/peers/contractor2_peer2/tls:/etc/hyperledger/tls
      # - ./poc-network/contractor2_peer2:/var/hyperledger/production      
    # depends_on:
    #   - contractor2_couchdb2
    networks:
      - poc

  # contractor2_couchdb2:
  #   container_name: contractor2_couchdb2
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - "10984:5984"
  #   volume:
  #     - ./poc-network/contractor2_couchdb2:/opt/couchdb/data
  #   networks:
  #     - poc       

  contractor2_cli:
    container_name: contractor2_cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=contractor2_cli
      - CORE_PEER_ADDRESS=contractor2_peer1:7051
      - CORE_PEER_LOCALMSPID=contractor2
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/contractor2/users/Admin@contractor2/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./contractor2-config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./config:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - poc
    depends_on:
      - contractor2_peer1
